In [3]:
import config

query_1a = """
SELECT 
    c.relname AS tabla,
    c.reltuples::bigint AS filas_estimadas,
    c.relpages AS paginas_estimadas,
    pg_size_pretty(pg_total_relation_size(c.oid)) AS tamano_total
FROM pg_class c
JOIN pg_namespace n ON n.oid = c.relnamespace
WHERE n.nspname = 'employees' AND c.relkind = 'r'
ORDER BY c.reltuples DESC;
"""
df_1a = config.run_query(query_1a)
df_1a

                 tabla  filas_estimadas  paginas_estimadas tamano_total
0               salary          2844047              18160       228 MB
1                title           443308               3200        44 MB
2  department_employee           331603               2160        29 MB
3             employee           300024               2504        26 MB
4   department_manager               24                  1        40 kB
5           department                9                  1        40 kB

In [4]:

query_1b = """
SELECT 
    c.relname AS tabla,
    a.attname AS columna,
    t.typname AS tipo_dato
FROM pg_class c
JOIN pg_namespace n ON n.oid = c.relnamespace
JOIN pg_attribute a ON a.attrelid = c.oid
JOIN pg_type t ON t.oid = a.atttypid
WHERE n.nspname = 'employees' 
  AND c.relkind = 'r' 
  AND a.attnum > 0 
  AND NOT a.attisdropped
ORDER BY c.relname, a.attnum;
"""
df_1b = config.run_query(query_1b)
df_1b

                  tabla        columna        tipo_dato
0            department             id           bpchar
1            department      dept_name          varchar
2   department_employee    employee_id             int8
3   department_employee  department_id           bpchar
4   department_employee      from_date             date
5   department_employee        to_date             date
6    department_manager    employee_id             int8
7    department_manager  department_id           bpchar
8    department_manager      from_date             date
9    department_manager        to_date             date
10             employee             id             int8
11             employee     birth_date             date
12             employee     first_name          varchar
13             employee      last_name          varchar
14             employee         gender  employee_gender
15             employee      hire_date             date
16               salary    employee_id             int8
17               salary         amount             int8
18               salary      from_date             date
19               salary        to_date             date
20                title    employee_id             int8
21                title          title          varchar
22                title      from_date             date
23                title        to_date             date

In [5]:

query_1c = """
SELECT 
    c.relname AS tabla,
    i.relname AS indice,
    ix.indisprimary AS es_llave_primaria,
    ix.indisunique AS es_unique,
    pg_get_indexdef(ix.indexrelid) AS definicion_columnas
FROM pg_index ix
JOIN pg_class c ON c.oid = ix.indrelid
JOIN pg_class i ON i.oid = ix.indexrelid
JOIN pg_namespace n ON n.oid = c.relnamespace
WHERE n.nspname = 'employees'
ORDER BY c.relname, i.relname;
"""
df_1c = config.run_query(query_1c)
df_1c

,tabla,indice,es_llave_primaria,es_unique,definicion_columnas
0,department,idx_16979_dept_name,False,True,CREATE UNIQUE INDEX idx_16979_dept_name ON emp...
1,department,idx_16979_primary,True,True,CREATE UNIQUE INDEX idx_16979_primary ON emplo...
2,department_employee,idx_16982_dept_no,False,False,CREATE INDEX idx_16982_dept_no ON employees.de...
3,department_employee,idx_16982_primary,True,True,CREATE UNIQUE INDEX idx_16982_primary ON emplo...
4,department_manager,idx_16985_dept_no,False,False,CREATE INDEX idx_16985_dept_no ON employees.de...
5,department_manager,idx_16985_primary,True,True,CREATE UNIQUE INDEX idx_16985_primary ON emplo...
6,employee,idx_16988_primary,True,True,CREATE UNIQUE INDEX idx_16988_primary ON emplo...
7,salary,idx_16991_primary,True,True,CREATE UNIQUE INDEX idx_16991_primary ON emplo...
8,title,idx_16994_primary,True,True,CREATE UNIQUE INDEX idx_16994_primary ON emplo...